### ISSUE TITLE
Add docker jobs to jenkins to push images to dockerhub for odpi-egeria.

### ISSUE THREAD

**Issue by schannamallu** [odpi/ci-management#101]
Add new github-maven-docker-merge job  for egeria-configure 

egeria-docker.yaml file

**Comment by schannamallu** [comment]
@planetf1 - Create a job for docker image build and Image push for configure. Can you check it and confirm. 
For now added 1 job, once you confirm I will add remaining 6 jobs.  

https://jenkins.odpi.org/view/egeria-docker/job/egeria-configure-maven-docker-verify-master-mvn35-openjdk8/2/console
https://cloud.docker.com/repository/docker/odpiadmin/egeria-configure

**Comment by planetf1** [comment]
The build is generally ok.

HOWEVER

It is pushing to 'odpiadmin'

It should be pushing to 'odpi'

I can see in the build
```
[egeria-configure-maven-docker-verify-master-mvn35-openjdk8] $ /w/tools/hudson.tasks.Maven_MavenInstallation/mvn35/bin/mvn -DGERRIT_BRANCH=master -Dsha1=origin/master -DMAVEN_OPTS= -DPROJECT=egeria -DMVN=/w/tools/hudson.tasks.Maven_MavenInstallation/mvn35/bin/mvn -DGERRIT_REFSPEC=refs/heads/master -DM2_HOME=/w/tools/hudson.tasks.Maven_MavenInstallation/mvn35 -DSTREAM=master -DARCHIVE_ARTIFACTS= "-DMAVEN_PARAMS=-Ddocker -Ddocker.repo=odpiadmin -Ddockerfile.useMavenSettingsForAuth=true -f open-metadata-resources/open-metadata-deployment/docker/configure" -DGERRIT_PROJECT=egeria --version
```
`-Ddocker.repo=odpi` is the correct setting (though the session should be authenticated through odpiadmin)

**Comment by schannamallu** [comment]
@planetf1  ok i will change to ODPI repo

**Comment by schannamallu** [comment]
@planetf1 ,

Add new docker jobs for atlas and apache-atlas.
Modify the repo from odpiadmin to odpi.

Can you check and confirm.
https://cloud.docker.com/u/odpi/repository/list

**Comment by planetf1** [comment]
yes they look good :-)

I noticed they are 'verify' builds. Of course all publish to docker hub. Do we just leave these running off a schedule without the other merge/stage builds?

**Comment by schannamallu** [comment]
@planetf1 Yes.we are leaving as it is. I assume merge and stage are not required for this. the verify is already scheduled as daily run."

**Comment by schannamallu** [comment]
@planetf1, Now added all the docker jobs. Can you check once.
I will close this issue

**Comment by planetf1** [comment]
I did take a look at the jobs. I think we do have a slight problem.

Currently the build is kicked off by 'verify' This means any PR will cause a new build, and push to docker hub (we don't have a staging mechanism). It's not critical as the volume of changes on the docker images isn't that high, but it would I think be preferable if rather than verify builds we just pushed after merge?

An even better option would be to kick off the build on PR, but hold off on pushing to docker hub (may require a change to the build). Or we push to a specific tag other than latest (also may need changes)

Will take a think on the best approach...

I also noticed some of the builds are now failing due to network issues......

**Comment by schannamallu** [comment]
@planetf1 ,
The problem is some of docker build are taking more than 1 hr. The Jenkins node make the longer builds to fail. Infra-team is investigating the problem .They come up with logs like Low RAM is causing the issue. I don't think so that cause the build fail. Let we wait 

Coming to Verify build ,yah for every PR its trigging the build. Build fail will cause the block PR

we can move verify to merge but there is slight problem during build as the build it calls a script 'maven-patch-release.sh' which makes build fail always. and also the merge job use the stage profile to transfer builds to nexus . In our case its is DockerHub.

I come with one approach  to reduce the build time 
i have seen the Dockerfiles which include Build and Actual images 

Cant we separate  these in two :
Build Dockerfile:
```
FROM ubuntu:18.10 AS build

# Install Git, which is missing from the Ubuntu base images.
RUN apt-get update && apt-get install -y git python openjdk-8-jdk maven wget inetutils-ping dnsutils gzip tar
RUN apt-get update && apt-get install -y git python openjdk-8-jdk maven wget libpostgresql-jdbc-java iputils-ping net-tools vim lsof apt-utils build-essential lsb-core lsb-release

ARG branch
ENV branch ${branch:-master}

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
ENV MAVEN_HOME /usr/share/maven
ENV PATH /usr/java/bin:/usr/local/apache-maven/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Working directory
WORKDIR /root

# Pull down Ranger and build it
RUN git clone http://github.com/apache/ranger.git -b ${branch}

# Remove -DskipTests if unit tests are to be included - build the code...
WORKDIR /root/ranger

# -Pall is normally used on non-linux platforms as it skips the native security plugins. However the -Plinux profile
# is currently pulling in a later maven assembly plugin as of 2018.11.05 which is breaking the build/packaging for
# the 1.2 branch....
RUN mvn -Pall -DskipTests=true clean compile package install assembly:assembly
RUN git log > /git.log && echo ${branch} > /git.branch && git remote -v > /git.remote
```

docker build -f Dockerfile.build -t odpi/ranger:master

For main Dockerfile

```
FROM odpi/ranger:master AS build
RUN mkdir -p /opt/ranger-admin
RUN tar xzf /root/ranger/target/ranger-*-admin.tar.gz --strip-components 1 -C /opt/ranger-admin

COPY dist/ranger-docker-start.sh /opt/ranger-admin/ranger-docker-start.sh
RUN chmod 755 /opt/ranger-admin/ranger-docker-start.sh

# Configure and install Solr locally
WORKDIR /opt/ranger-admin/contrib/solr_for_audit_setup
RUN sed -i 's|SOLR_INSTALL=false|SOLR_INSTALL=true|' install.properties
RUN sed -i "s|SOLR_DOWNLOAD_URL=|SOLR_DOWNLOAD_URL=http://www.mirrorservice.org/sites/ftp.apache.org/lucene/solr/7.7.1/solr-7.7.1.tgz|" install.properties
RUN ./setup.sh
RUN sed -i 's|^SOLR_JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"$|SOLR_JAVA_HOME="/usr/lib/jvm/java-1.8-openjdk"|g' /opt/solr/ranger_audit_server/scripts/solr.in.sh

WORKDIR /opt/ranger-admin
RUN sed -i "s|^DB_FLAVOR=MYSQL|DB_FLAVOR=POSTGRES|g" install.properties
RUN sed -i "s|^SQL_CONNECTOR_JAR=/usr/share/java/mysql-connector-java.jar|SQL_CONNECTOR_JAR=/usr/share/java/postgresql-jdbc.jar|g" install.properties
RUN sed -i "s|^audit_solr_urls=|audit_solr_urls=http://localhost:6083/solr/ranger_audits|g" install.properties

# Create minimal runtime image
FROM openjdk:8-jdk-alpine

LABEL org.label-schema.schema-version = "1.0"
LABEL org.label-schema.vendor = "ODPi"
LABEL org.label-schema.name = "ranger-admin-egeriavdc"
LABEL org.label-schema.description = "Apache Ranger administration server, for use as part of ODPi Egeria Virtual Data Connector demonstrations."
LABEL org.label-schema.url = "https://egeria.odpi.org/open-metadata-resources/open-metadata-deployment/"
LABEL org.label-schema.vcs-url = "https://github.com/odpi/egeria/tree/master/open-metadata-resources/open-metadata-deployment/docker/ranger"
LABEL org.label-schema.docker.cmd = "docker run -d -p 6080:6080 -p 6182:6182 -p 6083:6083 -p 6183:6183 -e PGUSER=postgres -e PGPASSWORD=passw0rd -e PGHOST=host -e RANGER_PASSWORD=admin999 odpi/ranger-admin-egeriavdc"
LABEL org.label-schema.docker.debug = "docker exec -it $CONTAINER /bin/sh"
LABEL org.label-schema.docker.params = "PGUSER=postgres user,PGPASSWORD=postgres password,PGHOST=postgres host,RANGER_PASSWORD=password to init for ranger admin user"

RUN apk --no-cache add python bash java-postgresql-jdbc bc shadow procps && apk --no-cache update && apk --no-cache upgrade

RUN groupadd -r ranger -g 1000 && useradd --no-log-init -r -g ranger -u 1000 -d /opt/ranger-admin ranger
RUN groupadd -r solr -g 1001 && useradd --no-log-init -r -g solr -u 1001 -d /opt/solr solr && mkdir -p /var/log/solr/ranger_audits && chown solr:solr /var/log/solr/ranger_audits

COPY --from=build --chown=ranger:ranger /opt/ranger-admin/ /opt/ranger-admin/
COPY --from=build --chown=ranger:ranger /git.* /opt/details/
COPY --from=build --chown=solr:solr /opt/solr/ /opt/solr/

# Once Solr is separated, we whould run this as the ranger user (non-root)
#USER ranger:ranger

WORKDIR /opt/ranger-admin

EXPOSE 6080 6182 6083 6183
ENTRYPOINT ["/bin/bash", "-c", "/opt/ranger-admin/ranger-docker-start.sh"]
```

For ranger:master build image  ,It is not necessary to build every time of PR
and we also  can create separate  jobs for Base Builder Images

This approach will make build time very less instead of hours

**Comment by schannamallu** [comment]
@planetf1, As per your above comment and we observed that docker verify job is triggering for each PR and which is flooding the jenkins with verify jobs.
Moved the docker jobs from verify job to stage jobs. So which will not trigger for every PR.
 https://github.com/odpi/ci-management/pull/107

So can you confirm this works for you.. If you agrees will merge this PR.
CC: @jwagantall

**Comment by planetf1** [comment]
yes it looks as if we no longer have the verification so agreed let's close this. thanks
