### ISSUE TITLE
Create INFO.Yaml file to ODPI

### ISSUE THREAD

**Issue by schannamallu** [odpi/ci-management#118]
Create INFO.Yaml file to ODPI
https://docs.releng.linuxfoundation.org/projects/global-jjb/en/latest/jjb/lf-ci-jobs.html#info-yaml-verify

**Comment by schannamallu** [comment]
@planetf1, 
As one the best to have requirement for release engineering team, we need to add one INFO.yaml file to all the repos which we are using in our project.
This INFO.yaml contains all the details regarding the project, committers and the approvers.

So can you check this sample file - https://github.com/onap/integration/blob/master/INFO.yaml
and add a INFO.yaml for our project in a same way?
Please let me know if you have any queries.

**Comment by planetf1** [comment]
* WHat are possible values of lifecycle_state
 * What about project_category
* What do entries like &onap_releng_ptl and *onap_releng_ptl mean in the sample
* Is there a particular format for issue tracking using git
* what does the repositories section mean
* Under tsc what are 'changes'
* Also we have a fair few committers in github - do we need to replicate them from the group there? 
* What date is project creation date? I guess inception into linux foundation?
* whats the format for mailing list
* How about realtime discussions (we use slack)

Some of this replicates information in our top level pom.xml (standard maven)

We can give it a go....

**Comment by planetf1** [comment]
cc: @mandy-chessell

**Comment by planetf1** [comment]
I opened up https://github.com/odpi/egeria/issues/1252 to track the change for egeria

**Comment by schannamallu** [comment]
Hi @planetf1 ,

Please find the below inline comments.

What are possible values of lifecycle_state
Suresh> Checking internally, will update you

What about project_category
Suresh> Checking internally, will update you

What do entries like &onap_releng_ptl and *onap_releng_ptl mean in the sample
Suresh> We can replace them to odpi_releng_ptl. Its just a format of yaml. We are redirecting the data to required fields.

Is there a particular format for issue tracking using git
Suresh> Can mention https://github.com/odpi/egeria/issues in url. And remaining parameters blank.

what does the repositories section mean
Suresh> List the name of the related repository names.

Under tsc what are ‘changes’
Suresh> If any new addition/deletion of committer or any other changes from the original in tsc we can mention that. Can be removed if none.
  
Also we have a fair few committers in github - do we need to replicate them from the group there?
Suresh> Yes. We need to add all the committers.

What date is project creation date? I guess inception into linux foundation?
Suresh> Looks like 7/31/18

whats the format for mailing list
Suresh> type: 'groups.io'
    url: 'lists.odpi.org'
    tag: '<[sub-project_name]>'

How about realtime discussions (we use slack)
Suresh> You can mention that.

**Comment by schannamallu** [comment]
Hi @planetf1 ,

Checked internally, for  lifecycle_state and project_category, its depends on the repo and the project.
Can check with the PM regarding this.

CC: @jmertic

**Comment by planetf1** [comment]
Please refer to the PR which is open for review at https://github.com/odpi/egeria/pull/1288
I will aim to merge on Monday if no further comments arise.
Any issues beyond that that relate to invalid entries please raise an issue (since I have no way of testing anything beyond yaml conformance)

**Comment by planetf1** [comment]
cc: @cmgrote this will need doing for the additional connector repos
cc: @mandy-chessell this may need doing for the data governance git repo

**Comment by schannamallu** [comment]
@planetf1, sorry could not able to check your changes early.

I reviewed now and some modifications needed in the INFO.yaml as below.

- <<: *onap_releng_ptl primary_contact: *odpi_releng_ptl project_lead: &odpi_releng_ptl
this  should be odpi_egeria_ptl

Since this is a github project the id: lines need to be  github_id:

Filename should be INFO.yaml not info.yaml

**Comment by cmgrote** [comment]
It looks like multiple repositories can be listed under the `repositories` portion of the file...  Should we create a separate `info.yaml` for each repository, or simply include the extra repositories in the core `egeria/info.yaml`?

If the latter is an option, I'd probably suggest going that way: as all of the other information (communications channels, maintainers, etc) will be the same...

**Comment by schannamallu** [comment]
@cmgrote , We prefer to have one INFO.yaml per repo even they are grouped repos.

**Comment by planetf1** [comment]
See referenced commit above. Please make any comments in the PR, I will merge in a day or two if I don't hear... I have no way of validating myself.

**Comment by schannamallu** [comment]
@planetf1, There are 2 changes requested in the PR.
- Change file name to INFO.yaml (capitals)
- Add TSC approvals link.

Sample - https://github.com/onap/integration/blob/master/INFO.yaml

**Comment by schannamallu** [comment]
@planetf1 , For now add this link to approvals: https://github.com/odpi/tsc should be fine and remaining blank.
Example:
tsc:
    approval: 'https://github.com/odpi/tsc'
    changes:
        - type: ''
          name: ''
          link: ''

**Comment by planetf1** [comment]
Ok done. updated PR and will merge once verification ok

**Comment by schannamallu** [comment]
LGTM

**Comment by schannamallu** [comment]
@planetf1 , PR was not raised to tsc approval changes. Can you raise a PR and merge that as well.

**Comment by planetf1** [comment]
apologies. just opened https://github.com/odpi/egeria/pull/1423 - I'd make the code change in my branch but as you say, no PR ...

**Comment by schannamallu** [comment]
@cmgrote - Can you update the INFO.yaml in all the repos in odpi.
And add the TSC approval link.  As mentioned in egeria repo - https://github.com/odpi/egeria/blob/master/INFO.yaml

**Comment by schannamallu** [comment]
@cmgrote  please file name should be change to info.yaml to INFO.yaml

**Comment by schannamallu** [comment]
@cmgrote Already changed file name  . sorry I did not see
