### ISSUE TITLE
Build error with mvn spotbugs and pmd scan in sonar job 

### ISSUE THREAD

**Issue by schannamallu** [odpi/ci-management#120]
Hi @planetf1 

Build error during spot bugs scan
of course, this scan consume memory so i put 
`MVN_OPTIONS=-Xmx5120m -XX:MaxPermSize=20148m -XX:ReservedCodeCacheSize=1024m
`

and cmd is 

`mvn $MVN_OPTIONS  -DfindBugs -Dsonar.java.spotbugs.reportPaths="target/spotbugsXml.xml" -Dsonar.java.pmd.reportPaths="target/pmd.xml"`

even if increase the memory still I got below error 

`15:18:59 [INFO] Open Metadata Open Types Test Resources ............ SUCCESS [  1.618 s]
15:18:59 [INFO] Open Types Test generator .......................... SUCCESS [ 25.967 s]
15:18:59 [INFO] Open Types Test execution 1.1-SNAPSHOT ............. FAILURE [19:58 min]
15:18:59 [INFO] ------------------------------------------------------------------------
15:18:59 [INFO] BUILD FAILURE
15:18:59 [INFO] ------------------------------------------------------------------------
15:18:59 [INFO] Total time: 01:09 h
15:18:59 [INFO] Finished at: 2019-07-05T09:48:59Z
15:18:59 [INFO] ------------------------------------------------------------------------
15:18:59 [ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:3.1.2:spotbugs (default) on project open-types-test: Execution default of goal com.github.spotbugs:spotbugs-maven-plugin:3.1.2:spotbugs failed: Java returned: 1 -> [Help 1]
15:18:59 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:3.1.2:spotbugs (default) on project open-types-test: Execution default of goal com.github.spotbugs:spotbugs-maven-plugin:3.1.2:spotbugs failed: Java returned: 1
15:18:59     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
15:18:59     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
15:18:59     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
15:18:59     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
15:18:59     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
15:18:59     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
15:18:59     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
15:18:59     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
15:18:59     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
15:18:59     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
15:18:59     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
15:18:59     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
15:18:59     at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
15:18:59     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
15:18:59     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
15:18:59     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
15:18:59     at java.lang.reflect.Method.invoke (Method.java:498)
15:18:59     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
15:18:59     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
15:18:59     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
15:18:59     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
15:18:59 Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.github.spotbugs:spotbugs-maven-plugin:3.1.2:spotbugs failed: Java returned: 1`

Can you please suggest the best method or Can we skip the last one 
`[INFO] Open Types Test execution 1.1-SNAPSHOT ............. FAILURE [19:58 min]`  
during the scan. 

Full log : https://jenkins.odpi.org/sandbox/view/All/job/odpi-egeria-sonar/5/console

**Comment by planetf1** [comment]
I tested locally (on a ubuntu system in the cloud) and was ale to run the full scan ok.

spotBugs should be excluded on the open meyadya packages via spotbugs-security-exclude.xml which includes:
```
<FindBugsFilter>
  <Match>
    <Package name="org.odpi.openmetadata.fvt.opentypes.*" />
  </Match>
</FindBugsFilter>
~
```

Will check my logs ...

**Comment by schannamallu** [comment]
> I tested locally (on a ubuntu system in the cloud) and was ale to run the full scan ok.
> 
> spotBugs should be excluded on the open meyadya packages via spotbugs-security-exclude.xml which includes:
> 
> ```
> <FindBugsFilter>
>   <Match>
>     <Package name="org.odpi.openmetadata.fvt.opentypes.*" />
>   </Match>
> </FindBugsFilter>
> ~
> ```
> 
> Will check my logs ...

@planetf1 , yah its working locally i have tested in my local self. working fine . The problem when the job run in Jenkins. I looking more option to solve that issue. e.g allocation more resource, modifying JVM options, MVN Options. 

i will update soon.

**Comment by schannamallu** [comment]
Its a JAVA Options issue.The job consumes more memory i tired to allocate the Xm settings from MVN_OPTIONS. Unfortunately these are not effected in the build. I finally got success by setting up the JVM Options.

Please find more log at https://jenkins.odpi.org/sandbox/view/All/job/odpi-egeria-sonar/11/

**Comment by planetf1** [comment]
Thanks for checking. I'll aim to run the findBugs build again - I hadn't noticed those reports of missing files (a little confusing - though there is an exclusion declared)

**Comment by planetf1** [comment]
I can confirm my local build failed with default memory, but passed with my alias, which I defined as 
```
➜  egeria git:(master) alias blds
blds='cd ~/src/egeria;MAVEN_OPTS="-Xmx5000M -Xss512M -XX:MaxPermSize=2048M -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC" unbuffer mvn clean install -DfindBugs -Dsonar.java.spotbugs.reportPaths="target/spotbugsXml.xml" -Dsonar.java.pmd.reportPaths="target/pmd.xml" -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS -DskipFVT 2>&1 | tee ~/logs/egeria-`date +%Y%m%d%H%M%S`-findbugs.log'
```

**Comment by schannamallu** [comment]
Hi @planetf1 ,

Thank you for the suggestion. unfortunately the suggestion is not working in Jenkins. Please have a look a log https://jenkins.odpi.org/sandbox/view/All/job/odpi-egeria-sonar-maven/2/console

i am trying with JAVA_OPTIONS before mvn cmd. i will let you know.

**Comment by planetf1** [comment]
I've just created a PR which I should merge later today - https://github.com/odpi/egeria/pull/1305

This will skip the open-types-test module for these additional scans, which I believe is the cause of the failures.

You may be able to experiment with reducing the memory after this PR, though I expect the default may still need an increase.

**Comment by schannamallu** [comment]
Hi @planetf1 ,
i have an implemented a solution for this scan through from global JJB which will take effect in the next week.
 The solution is simple i have added _JAVA_OPTION=Xmx5G before MVN cmd. This made the build success. 

Hope you you see the build pass in the next week.

**Comment by schannamallu** [comment]
@planetf1 

we have update the mvn arguments for pmd and spotbugs scan in prod env of jenkins.
while running the job i got pmd errors which cause the build failure. 

```
05:07:22 [INFO] --- maven-pmd-plugin:3.12.0:check (default) @ odf-metadata-api ---
05:07:22 [INFO] PMD Failure: org.odpi.openmetadata.commonservices.odf.metadatamanagement.rest.AnnotationRequestBody:9 Rule:UnusedImports Priority:4 Avoid unused imports such as 'org.odpi.openmetadata.commonservices.ocf.metadatamanagement.rest.FeedbackRequestBody'.
05:07:22 [INFO] PMD Failure: org.odpi.openmetadata.commonservices.odf.metadatamanagement.rest.AnnotationRequestBody:12 Rule:UnusedImports Priority:4 Avoid unused imports such as 'java.util.Objects'.
05:07:22 [INFO] PMD Failure: org.odpi.openmetadata.commonservices.odf.metadatamanagement.rest.DiscoveryAnalysisReportListResponse:10 Rule:UnusedImports Priority:4 Avoid unused imports such as 'org.odpi.openmetadata.frameworks.discovery.properties.DiscoveryEngineProperties'.
05:07:22 [INFO] PMD Failure: org.odpi.openmetadata.commonservices.odf.metadatamanagement.rest.DiscoveryAnalysisReportRequestBody:9 Rule:UnusedImports Priority:4 Avoid unused imports such as 'org.odpi.openmetadata.commonservices.ocf.metadatamanagement.rest.FeedbackRequestBody'.
05:07:22 [INFO] PMD Failure: org.odpi.openmetadata.commonservices.odf.metadatamanagement.rest.DiscoveryAnalysisReportRequestBody:11 Rule:UnusedImports Priority:4 Avoid unused imports such as 'org.odpi.openmetadata.frameworks.connectors.properties.beans.CommentType'.
05:07:22 [INFO] PMD Failure: org.odpi.openmetadata.commonservices.odf.metadatamanagement.rest.DiscoveryRequestRequestBody:9 Rule:UnusedImports Priority:4 Avoid unused imports such as 'org.odpi.openmetadata.commonservices.ocf.metadatamanagement.rest.ReferenceableRequestBody'.
05:07:22 [INFO] PMD Failure: org.odpi.openmetadata.commonservices.odf.metadatamanagement.rest.DiscoveryRequestRequestBody:10 Rule:UnusedImports Priority:4 Avoid unused imports such as 'org.odpi.openmetadata.frameworks.discovery.properties.DiscoveryRequestStatus'.
05:07:22 [INFO] PMD Failure: org.odpi.openmetadata.commonservices.odf.metadatamanagement.rest.DiscoveryRequestRequestBody:12 Rule:UnusedImports Priority:4 Avoid unused imports such as 'java.util.Date'.
05:07:22 [INFO] PMD Failure: org.odpi.openmetadata.commonservices.odf.metadatamanagement.rest.ODFOMASAPIRequestBody:47 Rule:UnusedFormalParameter Priority:3 Avoid unused constructor parameters such as 'template'..
05:07:22 [INFO] You have 9 PMD violations. For more details see: /w/workspace/odpi-egeria-sonar/open-metadata-implementation/common-services/odf-metadata-management/odf-metadata-api/target/pmd.xm
```

Please  find the  Jenkins console log : https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-sonar/350/console

**Comment by planetf1** [comment]
I checked the latest sonar build which ran today, and I am seeing sonar build failures
See https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-sonar/lastBuild/console

On PMD specifically - I don't think these are causing a failure. They are only reported to maven as INFO, so the build should continue. In the latest build the actual failure seems to be down to:

```
08:55:29 [ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:3.1.2:spotbugs (default) on project repository-services-implementation: Execution default of goal com.github.spotbugs:spotbugs-maven-plugin:3.1.2:spotbugs failed: Java returned: 1 -> [Help 1]
08:55:29 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:3.1.2:spotbugs (default) on project repository-services-implementation: Execution default of goal com.github.spotbugs:spotbugs-maven-plugin:3.1.2:spotbugs failed: Java returned: 1
08:55:29     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
```

I think this is down to running out of resources/memory ?

In fact I then looked further up the build log and see
```
08:55:28      [java] # There is insufficient memory for the Java Runtime Environment to continue.
08:55:28      [java] # Native memory allocation (mmap) failed to map 377487360 bytes for committing reserved memory.
08:55:28      [java] # An error report file with more information is saved as:
08:55:28      [java] # /w/workspace/odpi-egeria-sonar/hs_err_pid19951.log
08:55:28      [java] OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000007a6700000, 377487360, 0) failed; error='Cannot allocate memory' (errno=12)
```

is this fixable? 
Also can we increase to a daily run rather than weekly?

If we continue to have issues with pmd/spotbugs, we may need to remove the extra checks. This wouldn't be my favourite approach, but some results are better than none....

**Comment by planetf1** [comment]
@schannamallu  any news?

**Comment by schannamallu** [comment]
> @schannamallu any news?

i modified the maven parameters. Now its working 
https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-sonar/360/

**Comment by planetf1** [comment]
Thanks. let's close then & I'll reopen if we get issues
