### ISSUE TITLE
ODPi sonar scan is unstable

### ISSUE THREAD

**Issue by schannamallu** [odpi/ci-management#122]
The odpi-egeria sonar scan is unstable. 

It alternates between finding thousands of problems (correct :-( ) and finding none. The quality gate variues between red (as expected) and green (not true) 

If one reviews the activity on the top right of the page one can see the erratic results. 

I noticed for example a PR scan returns a good result 
https://github.com/odpi/egeria/pull/1245/checks?check_run_id=161950878 

https://jira.linuxfoundation.org/projects/IT/queues/custom/18/IT-16683,

**Comment by schannamallu** [comment]
@planetf1

 Hi Nigel,
AutoScan is in Beta version
The following languages are currently supported:
ABAP
Apex
CSS
Flex
Go
HTML
JS
Kotlin
PHP
Python
Ruby
Scala
Swift
TypeScript
TSQL
XML
for more info :

https://sonarcloud.io/documentation/autoscan/

**Comment by planetf1** [comment]
Thanks for the link. will review more.

So are all our scans now initiated by sonar auto scan? Or are we also doing manual builds?

**Comment by schannamallu** [comment]
Hi @planetf1 ,
we have both 
1. Auto scan from github
2. Sonar scan from jenkins (timer job)

**Comment by planetf1** [comment]
Thanks. So looking at the link I can select the dropdown 'master' and switch to any recent PR -- this is the auto scanning at work which is great.

The activity on 1.1-SNAPSHOT at https://sonarcloud.io/project/activity?id=odpi_egeria continues to show the constant pass/succeed which I assume is caused by these PRs and something we have no control over. As it's something they are still working on we should probably just close this as a known issue, we can't improve it.

But I did also notice another anomoly

Some of the scans show

```
QualityProfile: Use 'Sonar way' (Java)
```
whilst the others have:
```
QualityProfile: Use 'Sonar way' (HTML)
QualityProfile: Use 'Sonar way' (CSS)
QualityProfile: Use 'Sonar way' (JavaScript)
```

Is this something we can control? If so should we not be using the same profile for all scans?

**Comment by schannamallu** [comment]
@planetf1 
unfortunately sonar cloud has not provide control over sonar profiles. Its comes with default one which we cannot modify.

**Comment by planetf1** [comment]
I'm still concerned by the way the status is constantly going from red to green .I can see technically why, but I'll post to the sonarcloud forum to ask for clarification

**Comment by planetf1** [comment]
Posted for clarification to https://community.sonarsource.com/t/constant-pass-fail-after-using-auto-scanning/11896

**Comment by planetf1** [comment]
I wonder if by implementing #120 we are making the sonar scanning more confusing. 

Ideally I'd like to see
 - the graphs represent the trend in full scans (as full as we can make them wrt findbugs/pmd IF WE CAN) - will be red for now, but show improvement
 - PR scans for added checks prior to any merges.

I suggest seeing how the forum post reply goes - I think we might need some advice from sonarcloud

**Comment by schannamallu** [comment]
HI @planetf1 ,
i assume the Egeria project in sonar cloud is updating for every scan say from PR and from Jenkins.
when it update from PR it goes red to green since the auto scan does not support for QualityProfile: Use 'Sonar way' (Java) 
where from Jenkins it goes for full scan , the Quality gate move form Green to RED. 

I hope its sonar default behavior, Any way i also looking reply from the sonar cloud team.

**Comment by planetf1** [comment]
Having read the docs at https://sonarcloud.io/documentation/autoscan/ it's clear that currently AutoScan does not support Java - so your description is perfectly correct :-)

As such I think we have minimal value from autoscan, and it's adding confusion.

The auto PR check is a nice to have (we found one bug that way) but with very limited scope (as most of our code is java) I think we can go without it.

ie I think disabling autoscan would be a good choice - at least until it supports java
This would mean both any scheduled scan and the new PR check

**Comment by schannamallu** [comment]
Hi @planetf1 ,
i removed the Sonar Auto Scan from Github.
https://github.com/odpi/egeria/settings/installations. 

Please check and let me know.

**Comment by planetf1** [comment]
Sonar scans look better, though I noticed coverage data was unavailable.
My bad - a prior fix caused a regression
See https://github.com/odpi/egeria/pull/1312

So I think this can be closed as at least in my PR (to be merged later) jacoco exec files are building again (they weren't)

**Comment by schannamallu** [comment]
@planetf1  I am closing the issue and open issue on jacoco reports issue with sonar

**Comment by planetf1** [comment]
I think Jacoco is fine now. We have coverage data. And the scans worked ok.... but I think we could benefit from daily scans rather than weekly

**Comment by schannamallu** [comment]
> I think Jacoco is fine now. We have coverage data. And the scans worked ok.... but I think we could benefit from daily scans rather than weekly

@planetf1: It is configured for a daily scan not weekly scans.

**Comment by planetf1** [comment]
Ah. Thanks for confirming it is indeed daily
