### ISSUE TITLE
Jacoco reports are not displayed in SonarCloud

### ISSUE THREAD

**Issue by schannamallu** [odpi/ci-management#127]
@planetf1
Sonar scans look better, though I noticed coverage data was unavailable.
My bad - a prior fix caused a regression
See odpi/egeria#1312

So I think this can be closed as at least in my PR (to be merged later) jacoco exec files are building again (they weren't)

**Comment by planetf1** [comment]
Can close now

**Comment by schannamallu** [comment]
> Can close now

Thanks for the update, I am closing. 
Thanks
