### ISSUE TITLE
Sonar Report Upload Failure for Egeria in Jenkins

### ISSUE THREAD

**Issue by schannamallu** [odpi/ci-management#22]
Last Analyzed time is showing on November.
URL:
https://sonar.odpi.org/dashboard?id=org.odpi.egeria%3Aegeria

Fix it to show the build date and time stamp.

**Comment by planetf1** [comment]
This is becoming more important as we've been trying to work with the public sonarcloud instance at https://sonarcloud.io/dashboard?id=planetf1_egeria , but are now getting issues as per https://community.sonarsource.com/t/server-analyzing-outofmemoryerror-timeout/6037

Also whilst the abstract of this issue refers to the timestamp, the reports are not there at all.

**Comment by schannamallu** [comment]
Hi Nigel,

I thought it was an timestamp issue, and we ran some sonar test in sandbox and realized that the issue is with the sonar.

API Log for Sonar report - https://sonar.odpi.org/api/ce/task?id=AWhshNkYewVAfYmV9n_d
1) Java Heap space issue
2) Data Storage issue in database (Blob size exceeds the maximum).

I'll change the Issue Topic to **Sonar Report Upload  Failure for Egeria in Jenkins**

**Comment by schannamallu** [comment]
Hi Nigel, 

We have a patch to increase the sonar heap dump memory to 2048mb, after applying this patch we need to restart sonar, I assume the odpi devs/project members has to approve for the restart, so please conform with the  team and let me know the suitable timing to apply this patch and restart.

**Comment by planetf1** [comment]
Please feel free to reboot at your convenience...

**Comment by schannamallu** [comment]
Code is merged and sonar memory is upgraded, started the sonar test job(odpi-egeria-sonar) in sandbox jenkins, will publish the results once the job is done.

**Comment by schannamallu** [comment]
We worked closely with our it-infra team to increase the heap size of various parameters like

We tried increasing the web java opts
sonarqube::web_java_opts: '-Xmx2048m’.    ——    Failed

We tried increasing search engine and compute engine opts.
sonar.search.javaOpts=-Xmx1536m -Xms512m -XX:+HeapDumpOnOutOfMemoryError.   ——  Failed
sonar.ce.javaOpts=-Xmx1536m -Xms512m -XX:+HeapDumpOnOutOfMemoryError.    ———   Failed

Now another option is to increasing the instance size from c4.large to c4.xlarge that’ll increase the instance memory capacity from 4gb to 8gb 

Discussing on this fix with it-infra, I’ll let you know once this is done and I’ll test it.

**Comment by schannamallu** [comment]
Sonar scanner is fixed, Changes did to made it work
**Changes:**
1) Changed AWS sonar instance size from c4.large to t3.large (doubling memory at negligible cost difference)
2) Increased max Search heap memory size from 512mb to 2.5gb.
3) Increased max ComputeEngine heap memory size from 512mb to 4gb.

**Result:**
Jenkins Build URL: https://jenkins.odpi.org/sandbox/view/All/job/odpi-egeria-sonar/3/console
Sonar URL: https://sonar.odpi.org/dashboard?id=org.odpi.egeria%3Aegeria
Sonar API URL: https://sonar.odpi.org/api/ce/task?id=AWiaFHekBAfKAxtN8m3Q

**Attached Sonar ScreenShot for your reference**
![screen shot 2019-01-29 at 1 29 26 pm](https://user-images.githubusercontent.com/41459780/51931137-1b4e6800-23ca-11e9-8c22-05a776b50fa3.png)
![screen shot 2019-01-29 at 1 29 43 pm](https://user-images.githubusercontent.com/41459780/51931142-1f7a8580-23ca-11e9-983c-3bbd6d12ef3d.png)
![screen shot 2019-01-29 at 1 30 33 pm](https://user-images.githubusercontent.com/41459780/51931148-22757600-23ca-11e9-9ffa-9d480adde2bb.png)

**Comment by schannamallu** [comment]
Please test this and let me know the status, so that i can close this issue.

**Comment by schannamallu** [comment]
Hi Nigel,

Thanks for your confirmation on this fix, i'm closing this issue.
