### ISSUE TITLE
Update Sonar Rules to ignore duplicate code errors.

### ISSUE THREAD

**Issue by schannamallu** [odpi/ci-management#34]
'''How can we tweak the Sonar rules. For example as per https://docs.sonarqube.org/7.4/project-administration/narrowing-the-focus/ we are interested in ignoring issues in generated code (for now) ie java code that uses @generated. In truth we'd probably like to narrow it down to only ignoring duplicate code errors in generated code - not other bugs. this may need a little experimentation. Can we change the rules or is it only an admin task?'''   ---   Nigel,

This is not an admin task, we can tweak our own sonar rules, let me know the ignore rules, so that i can update the sonar rules by adding them.

Reference URL: https://docs.sonarqube.org/7.4/project-administration/narrowing-the-focus/

**Comment by planetf1** [comment]
I do not appear to have access to change rules - so can you update permissions or indicate how to achieve this? Thanks

**Comment by schannamallu** [comment]
Ok sure i'll update the rules, is there any particular rules we need to update in sonar, please give me the ruleset if you have or provide me the scenario's which need to be added as ruleset in sonar.

**Comment by planetf1** [comment]
This is what I have on sonarcloud.
Administration -> General Settings -> Analysis Scope -> Cover Coverage -> Coverage Exclusions
```
**/generated/**
```

**Comment by schannamallu** [comment]
Can you please point us to the java code location( ie java code that uses @generated), and any sonar rules that are already existing in the system currently

We are aware of below navigation
Administration -> General Settings -> Analysis Scope -> Cover Coverage -> Coverage Exclusions
and updated with generated value. please check and let us know

Duplications:
Please let us know which files to be included for duplications

**Comment by planetf1** [comment]
Co-incidentally the biggest amount of generated code was refactored in the last few days... So will review sonar report. At the same time other code has been added recently.

I'll see if we can annotate the code with @generated, and see if this addresses the sonar scan

**Comment by planetf1** [comment]
Reading the sonar docs, sonar doesn't really understand @generated it seems... 

it is possible to add a rule to exclude all code ith @generated in the file - though this is a basic check and wouldn't account for files where some methods are generated, some not.

The docs give an example of:
Ignore all issues in files containing "@javax.annotation.Generated"
@javax\.annotation\.Generated

This would cause ALL checks to be skipped. Even better would be to try skipping only the duplicate checks. https://docs.sonarqube.org/latest/project-administration/narrowing-the-focus/#NarrowingtheFocus-IgnoreIssues offers some help, though I haven't had a chance yet to try this out in sonar. Are you familar with how one might do this?


See also
https://github.com/odpi/egeria/issues/865

**Comment by schannamallu** [comment]
@planetf1 , Updated the duplicate rules from Administration > General Settings > Analysis Scope > Duplications  as below:
![Screen Shot 2019-04-01 at 2 15 58 PM](https://user-images.githubusercontent.com/41459780/55349967-f2f5ef00-5488-11e9-85d3-7b68c7979287.png)

**Comment by planetf1** [comment]
we can close this, as it has been changed as requested :-)
