### ISSUE TITLE
Stage and release with different branches

### ISSUE THREAD

**Issue by iotivity-replication** [odpi/ci-management#35]
Releasing egeria code using different branch like egeria-release-1.0/egeria-release-1.1 so on.

**Comment by iotivity-replication** [comment]
Comment from Nigel
'''
master
 - used for ongoing development work
 - has to be kept open for work at all times. no freezing.
 - developers work on 'feature' branches IN THEIR OWN FORK (anything from a one liner to 100s of files, but often smaller pieces of work)
 - PRs used to pull into master
 - Pom version will typically point to the next release ie 0.3-SNAPSHOT
 - pom version is currently 1.1-SNAPSHOT (after Mandys update)
 
egeria-release-1.0 (and 1.1, 1.2, 1.3 etc every 1-2 months)
 - pom version has been MANUALLY changed to 1.0
 - this is the code we want to release
 - no code changes are planned (we could make a fix if any serious issue found)
 
So the most urgent/main gap we have is
 - pushing maven artifacts from egeria-release-1.0 to maven central (and also to our local nexus 'release' repository)
 - includes GPG signing
 
For our next release
 - how to address this process better/ more automated
 - clear step by step instructions identifying responsibilities 
 - understanding limitations, caveats
 
A workable future process to me would need to include
 - Our team creating a branch when we want to stabilise some code ready for release as that allows us to isolate the code from work on master - I'm not sure how else we can ad stability and avoid blocking master. 
 - understand who should make pom version changes, us or automation
 - after a little work deciding we want to create a release candidate
 - doing something (PR? git tag etc..., jenkins build, email) to ask for a release candidate to be created (maven artifacts)
 ... a little more testing
 - doing something else to ask for the final release
'''

**Comment by schannamallu** [comment]
https://github.com/odpi/ci-management/issues/38
