### ISSUE TITLE
Maven verification build not launched - ODPi Egeria

### ISSUE THREAD

**Issue by iotivity-replication** [odpi/ci-management#37]
Last night I submitted a PR https://github.com/odpi/egeria/pull/778
Checks ran against it ok
 
Today I added a new commit to the PR.
The check status in the PR changed to '**Maven Verify ** Expected — Waiting for status to be reported'
However no build results appeared - and no build was launched in jenkins https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-maven-verify-master-mvn35-openjdk8/
I added 'recheck' as a comment, but still no build
I then tried a dummy commit, which did update status in the PR -- but still left the check status as waiting for status
I could STILL see no build active in jenkins
 
So it seems as if PR builds are currently not working
 
This has happened a number of times before too - is there something that is failing in the process?
 
Many thanks
Nigel.

**Comment by iotivity-replication** [comment]
To test this issue could you please create a new pull request, so that i can test by adding some comment to 'recheck' or 'retest'.

**Comment by schannamallu** [comment]
Maven verification build not launched - ODPi Egeria #41
