### ISSUE TITLE
Maven verification build not launched - ODPi Egeria

### ISSUE THREAD

**Issue by schannamallu** [odpi/ci-management#41]
from Nigel
" Last night I submitted a PR [odpi/egeria#778](https://github.com/odpi/egeria/pull/778)
Checks ran against it ok

Today I added a new commit to the PR.
The check status in the PR changed to '**Maven Verify ** Expected — Waiting for status to be reported'
However no build results appeared - and no build was launched in jenkins https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-maven-verify-master-mvn35-openjdk8/
I added 'recheck' as a comment, but still no build
I then tried a dummy commit, which did update status in the PR -- but still left the check status as waiting for status
I could STILL see no build active in jenkins

So it seems as if PR builds are currently not working

This has happened a number of times before too - is there something that is failing in the process?

Many thanks
Nigel.

**Comment by schannamallu** [comment]
To test this issue could you please create a new pull request, so that i can test by adding some comment to 'recheck' or 'retest'.

**Comment by planetf1** [comment]
Possibly related, but as of this morning no builds have run for 2.5 hours, though there are jobs in the jenkins build queue. The difference may be that this could just be a delay whilst in the above case the request gets lost.

If you need a PR to experiment with I suggest using https://github.com/odpi/egeria/pull/529 which we've already been using to run CLM

**Comment by schannamallu** [comment]
Added a comment 'retest this please' in PR https://github.com/odpi/egeria/pull/529 and the jenkins maven verify build got triggered and this is the build no https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-maven-verify-master-mvn35-openjdk8/617/console

Please test from your end and let me know.

**Comment by planetf1** [comment]
I think the problem is that in the past we saw it work most of the time, but occasionally fail. The example above was a specific example where it failed.

We now seem to have a problem where no builds are working at all in mornings -- so it's difficult to isolate the issues.

I suggest I'll close this ,and reopen with the next specific instance that fails, after the general build issues are resolved

**Comment by planetf1** [comment]
(I can't close this)

**Comment by schannamallu** [comment]
@planetf1, Today I fixed some cloud config related issue. This should fix the issue. Can you observe the builds and update this ticket.

**Comment by planetf1** [comment]
will check over next few days and report back

**Comment by schannamallu** [comment]
I think every think looks good . So i am closing this issue.

**Comment by planetf1** [comment]
ok. not seen issues since
