### ISSUE TITLE
Adding Support for JaCoCo test coverage

### ISSUE THREAD

**Issue by schannamallu** [odpi/ci-management#42]
Adding support for JaCoCo test coverage in jenkins for egeria project

Nigel Comment
'''
 The sonar 'test coverage' checks will require us to add jacoco to our build process so that we capture unit test logs properly. When the sonar build runs, does it also build the code? I assumed not... in which case where can it get test coverage data from? Where do we tell jacoco to put coverage logs? How do other projects manage this?
'''

Reference HelpDesk Ticket
https://rt-sso.linuxfoundation.org/Ticket/Display.html?id=65614

**Comment by planetf1** [comment]
The egeria build currently puts the unit test coverage data in target/jacoco.exec

We are seeing coverage data in sonar now, so it looks as if this is being picked up automatically?
Does everything look ok on the sonar server? If so I suggest we close.

**Comment by schannamallu** [comment]
Do you need the sonar jacoco plugin to be installed in sonar, it allows you to load the JaCoCo data from its XML format for all the languages for which you can generate a JaCoCo report, It means you can load the JaCoCo data related to Java.

if you are able to see the jacoco data in sonarqube and If you want to load the jacoco data using sonar please let me know  i'll install the jacoco plugin in sonarqube.

**Comment by planetf1** [comment]
It may already be installed? I do see non-zero coverage figures now.
Our maven build process (when run with mvn clean install) will populate coverage data into target/jacoco.exec - so perhaps this is working ok.

**Comment by schannamallu** [comment]
thanks for confirmation ! closing this issue
