### ISSUE TITLE
Create Java 11 build

### ISSUE THREAD

**Issue by planetf1** [odpi/ci-management#62]
Java 11 is the current LTS. Whilst Egeria is building and running with Java 8 for now, we would like to be prepared for the future.

This build should initially be non-blocking (ie on a PR) especially as we need to fix https://github.com/odpi/egeria/issues/916 first

Java should be openjdk - either from distro or adoptopenjdk.net and should be at the 'latest' version

**Comment by schannamallu** [comment]
@planetf1, So Java 11 build is part of (required for) issue #65 rite?

**Comment by planetf1** [comment]
Hi,
 The issues are independent.
 This refers to the existing egeria project build - which we want to replicate for Java 11.

 I would defer to @cmgrote as to whether he needs both Java 8 and Java 11 for the IGC components, or just 8.

**Comment by cmgrote** [comment]
I think we should go for parity — keep both aligned (so both 8 and 11).

**Comment by schannamallu** [comment]
@planetf1 @cmgrote .. Ok.. I will work on that and will update you.

**Comment by schannamallu** [comment]
Hi @planetf1  @cmgrote - I have added job maven-verify-master-mvn35-openjdk11 for java 11 builds.
Before committing it I have a questions.
So for making it non blocking can we make them as non required from the git side? Will that work ?

**Comment by planetf1** [comment]
Yes I think that should work

**Comment by planetf1** [comment]
I've noticed we now have a maven verify java 11 build, but have noticed two issues
 a) The java 11 build doesn't actually seem to invoke maven to build the code

 b) Some users today have complained that the maven verify check initially goes red - linked to a java
 11 failure, and then goes green -with java 8, so I don't know if the two jobs are now contatenated? This seems a little confusing. I've not seen myself yet

**Comment by planetf1** [comment]
Are both builds trying to update the same status? Could that explain the confusing behaviour? This is also affecting the links to status from the PR

**Comment by schannamallu** [comment]
@planetf1, Yes both the jobs are trying to update the same check. 
As I checked the build config, its using same check name for jdk8 and jdk11.

This fix will go into a common component. So it may take some time.

So, apart from the check updating multiple time is it blocking anything in current PRs?

**Comment by planetf1** [comment]
The concern is that the Java 11 build could result in a failure on the core Java 8 build (ie not allowing a PR to be merged). 

I wonder if we might be best leaving the java 11 build off until we can use a seperate check name?

**Comment by schannamallu** [comment]
@planetf1  Sure, will disable java 11 build for now..

**Comment by schannamallu** [comment]
@planetf1 ,It should work as expected now.. Can you check it.

**Comment by planetf1** [comment]
@schannamallu I am seeing a build now reporting as UNSTABLE. The maven portion has worked ok, but the build script tail end seems to have some issues.

This will significantly impact us..
FOr example This PR
https://github.com/odpi/egeria/pull/1035
Links to a java 11 build for the check
https://jenkins.odpi.org/job/odpi-egeria-maven-verify-master-mvn35-openjdk11/54/console
Which is UNSTABLE

In summary:
 a) We need java 8 build to be reliable, and act as a gating check on PRs (as before)
 b) We would like java 11 builds to not act as a gating check. This will help us prepare, but it must not comprimise a) above as we get them setup. The maven portion of this build seems ok, so the script error may be specific to this. As I mentioned before, we really need this to be a seperate check as far as github is concerned.

Potentially all builds are broken so we do need a) addressed ASAP

Thanks.

cc: @mandy-chessell

**Comment by schannamallu** [comment]
Hi @planetf1 
We have updated the global JJB version after that the unstable  problem araise. Allow some time i will discuss with team and let you know.

**Comment by planetf1** [comment]
Still failing.

See 
https://jenkins.odpi.org/job/odpi-egeria-maven-verify-master-mvn35-openjdk11/55/console
https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-maven-verify-master-mvn35-openjdk8/1010/console

BOTH java 8 and java 11 look fine from a maven perspective (success) but end with status UNSTABLE

This is blocking us ... Would appreciate if you could investigate asap cc: @mandy-chessell @jmertic

**Comment by schannamallu** [comment]
Hi Nigel,

I think everything is good now..BOTH java 8 and java 11 looks good  ..no unstable 

Thursday and Friday I am out of office..I will be back on Monday .

Thanks
Suresh

**Comment by planetf1** [comment]
Thanks. rechecking a PR now

**Comment by askb** [comment]
Hello @planetf1: 

I've reviewed the jobs in question which were in an unstable state, these are going through now with the latest PR merged [1.] a few hours ago and global-jjb updated to v0.37.5. If you notice similar errors, please a "recheck" or "remerge" comment should retrigger the jobs with the latest changes.

[1.] https://github.com/odpi/ci-management/pull/80

Cheers.
Anil

**Comment by planetf1** [comment]
Thanks. I can confirm builds are working now.

(Leaving this issue open to continue the changes to support Java 11 build verification)

**Comment by schannamallu** [comment]
@planetf1   I think it was working good. so can i close this issue?

**Comment by planetf1** [comment]
Can you clarify the current behaviour?

We have one github status check for a verification build 
Is it only the Java 8 build that is updating this now?

That's a first step.

In future would you expect to add another status check for Java 11 ?
It would be ideal if this linked to the build log, so that anyone working on a PR knows they have broken Java 11
However we would want to allow the commit to continue, as long as Java 8 is ok.

Is this possible?

**Comment by schannamallu** [comment]
@planetf1, Currently both Java8 and java11 jobs updating the same status check.

 We have added a new feature in our global-jjb component which is yet to release.
 This new feature will show multiple status check names like `Maven verify java8` and `Maven verify java11` in the PR.

For now I will stop the verify job for java11. As both java8 and java11 updating the same check in the github PR.

Will update you once the new feature is released and will enable the verify job for java11.

**Comment by schannamallu** [comment]
@planetf1 , Do you want me to enable the maven verify jobs for opnjdk8 and opnjdk11..?
And you want multiple java version support only for the maven verify job rite?

**Comment by planetf1** [comment]
My concern would be  whether it will make the verification step longer. I'll also need to gather agreement from the broader development team. Will they run in parallel?

I can ask the question and get back to you - probably after our next team call on tuesday

**Comment by schannamallu** [comment]
@planetf1, The verify job config for java8 and java11 are same. So, both will be triggered when a PR is raised. 
But we can make java11 as non blocking from the github side.
You can check this option and let me know so I will implement.

**Comment by planetf1** [comment]
Ok let's go with non-blocking for java11 initially. If it works out well we may switch to blocking later.
Thanks

**Comment by schannamallu** [comment]
@planetf1 , Added the java11 support. And its non blocking.
Can you please verify.

**Comment by planetf1** [comment]
Super. Thanks. That's looking good now. 

I will raise a new request when we wish to switch to required.
