### ISSUE TITLE
Integrate jenkins build jobs for github pull requests

### ISSUE THREAD

**Issue by schannamallu** [odpi/ci-management#65]
Integrate jenkins build jobs for github pull requests

Setup the same controls we have on Egeria core on this repository as well

Things like:

automated Jenkins build
review as optional
https://github.com/odpi/egeria-connector-ibm-igc/pull/1#issuecomment-487052707

Options

**Comment by schannamallu** [comment]
@planetf1  can i close this issue?

**Comment by planetf1** [comment]
@cmgrote ?

**Comment by cmgrote** [comment]
Yes, sorry -- looks good now, thanks!
