### ISSUE TITLE
Compilation error while building docker images

### ISSUE THREAD

**Issue by schannamallu** [odpi/ci-management#85]
@planetf1  i got below error while running mvn clean install -Ddocker 

Please find the more details 
`https://jenkins.odpi.org/sandbox/view/All/job/odpi-egeria-docker/15/console`
note : If you want generate the same error in local please delete the ~/.m2/  repo & run the mvn command
 
```
[INFO] [ERROR] COMPILATION ERROR : 
[INFO] [INFO] -------------------------------------------------------------
[INFO] [ERROR] /root/atlas/open-metadata/src/main/java/org/apache/atlas/openmetadata/admin/server/spring/OpenMetadataAdminResource.java:[27,48] cannot find symbol
[INFO]   symbol:   class VoidResponse
[INFO]   location: package org.odpi.openmetadata.adminservices.rest
[INFO] [ERROR] /root/atlas/open-metadata/src/main/java/org/apache/atlas/openmetadata/admin/server/spring/OpenMetadataAdminResource.java:[107,12] cannot find symbol
[INFO]   symbol:   class VoidResponse
```

**Comment by planetf1** [comment]
Thanks. will look. I was able to build manually yesterday (but with a local m2).

**Comment by planetf1** [comment]
Note that this occurs when building the Apache Atlas docker image. In fact the docker build itself calls maven to build atlas. It is currently using our own fork with Egeria integration added. That integration requires our Egeria maven artifacts which it gets from the maven snapshot repo.

It looks as if the build was running only on part of the full egeria tree ie:
open-metadata-resources/open-metadata-deployment/docker

I've normally built from top, however for just the artifacts this does make sense (faster). I will try that configuration with a clean m2 locally.

**Comment by planetf1** [comment]
I can confirm the same error when running locally from
open-metadata-resources/open-metadata-deployment/docker
with
```
mvn clean install -Ddocker -Ddocker.repo=odpi
```

**Comment by planetf1** [comment]
Also the same occurs when building complete from top level - a process that worked yesterday.

The errors suggest a mismatch between the egeria artifacts being picked up from the nexus repository, and the modified atlas code in git. 

I will have to investigate further tomorrow.

**Comment by planetf1** [comment]
Code issue identified - atlas fork needs updating. 
Will track fix in referenced issue & report back here when ready to rebuild.
