### ISSUE TITLE
Add new tab 'odpi - igc connector'

### ISSUE THREAD

**Issue by schannamallu** [odpi/ci-management#88]
Add new tab 'odpi - igc connector'.  this tab should be renabled to something like 'odpi - igc connector

'https://rt-sso.linuxfoundation.org/Ticket/Display.html?id=75788

**Comment by schannamallu** [comment]
@planetf1, can i close issue?

**Comment by planetf1** [comment]
Yes.

We may have to rethink our naming/tabs as we add more projects under odpi. But that's down to the projects to figure out :-)

**Comment by planetf1** [comment]
Actually - why do we now have both egeria and odpi-egeria populated?
I presume the egeria tab will go

**Comment by schannamallu** [comment]
@planetf1, Removed the extra egeria tab. 
Can you check and confirm.

**Comment by planetf1** [comment]
yes that looks good thanks

**Comment by schannamallu** [comment]
@planetf1  closing this issue?

**Comment by planetf1** [comment]
yes please
