### ISSUE TITLE
CLM builds appear on both the egeria & odpi-egeria tab

### ISSUE THREAD

**Issue by schannamallu** [odpi/ci-management#89]
https://rt-sso.linuxfoundation.org/Ticket/Display.html?id=75788
CLM builds appear on both the egeria & odpi-egeria tab, but I presume should only appear under the CLM tab

**Comment by schannamallu** [comment]
@planetf1,
CLM jobs should show up in two places:
1) The CLM tab itself
2) The tab for the repository in which it is running (aka the project specific tab)

**Comment by planetf1** [comment]
ok thanks for clarification

**Comment by schannamallu** [comment]
@planetf1  can i close issue?

**Comment by planetf1** [comment]
yes please close
