### ISSUE TITLE
igc connector builds Failing

### ISSUE THREAD

**Issue by schannamallu** [odpi/ci-management#90]
All of the builds under egeria are failing (these are the igc connector builds).the clm build for igc is also failing
https://rt-sso.linuxfoundation.org/Ticket/Display.html?id=75788

**Comment by schannamallu** [comment]
@planetf1,

in our terms , while build going to nexus release then remove the -SNAPSHOT word from the pox.xml and deploy to nexus.

In this case unfortunately the dependencies also has version tag of SNAPSHOT say, `<open-metadata.version>1.1-SNAPSHOT</open-metadata.version>` in pom.xml at https://github.com/odpi/egeria-connector-ibm-igc/blob/master/pom.xml

During  jenjkins build, jenkins  delete the -SANPSHOT string from pom. this makes the build failure by calling not exit url jars.

Please find the build log https://jenkins.odpi.org/view/egeria/job/egeria-connector-ibm-igc-maven-stage-master/27/console

i believe we need to make the jjbs more mature.
![image](https://user-images.githubusercontent.com/41459780/58583836-e391e880-8222-11e9-99a1-b5267c9d4f28.png)

**Comment by planetf1** [comment]
This is closely related to the release process discussed at https://github.com/odpi/ci-management/issues/43

The lftools scripts I found seemed to do a global search (all files) but this job is specifically targetting .xml only.

We need to refer to the release not only in POMs, but also in documentation links, docker build steps etc. Our manual approach to this for initial egeria releases was a global search/replace of all text files (in intellij), coarse, but it works.

If the egeria build is also similar to above and just looking for *.xml, the build will not be good. I think either the scripts need to do nothing and work ok with us having manually changed the release numbers, OR they need to change ALL references.

**Comment by schannamallu** [comment]
@planetf1  Can i close this issue?

**Comment by planetf1** [comment]
Yes. Please close. The current build failures as business as usual - our project needs to fix the code

**Comment by schannamallu** [comment]
@planetf1 Thanks
