### ISSUE TITLE
Jenkins for egeria-connector-apache-atlas

### ISSUE THREAD

**Issue by cmgrote** [odpi/ci-management#93]
New repository odpi/egeria-connector-apache-atlas -- ideally should have the same Jenkins build setup as other repos (eg. odpi/egeria-connector-ibm-igc).

**Comment by schannamallu** [comment]
@cmgrote, Added jenkins build jobs for new repo. Can you please check and confirm.

**Comment by cmgrote** [comment]
Works great, thanks!  Are you able to remove the mandatory review check on PRs as well (for that same repo)?

**Comment by schannamallu** [comment]
@cmgrote, Thanks for the update. For the mandatory review check, changes should be done from the github side. Jenkins side we only setup the jobs.

**Comment by schannamallu** [comment]
@cmgrote  can i close issue?

**Comment by cmgrote** [comment]
Done 😉
