### ISSUE TITLE
JJB build fails

### ISSUE THREAD

**Issue by schannamallu** [odpi/ci-management#94]
I noticed the JJB build at https://jenkins.odpi.org/view/ci-management/job/ci-management-jjb-deploy-job/lastBuild/ is failing
Unsure of impact but may need tidying up

**Comment by schannamallu** [comment]
@planetf1  it was fixed . please can you check 
https://jenkins.odpi.org/view/ci-management/job/ci-management-jjb-deploy-job/

**Comment by planetf1** [comment]
yes, fixed. thanks
