### ISSUE TITLE
CLM build for egeria lists as UNSTABLE - but given the reports, perhaps this is as expected 

### ISSUE THREAD

**Issue by schannamallu** [odpi/ci-management#96]
CLM build for egeria lists as UNSTABLE - but given the reports, perhaps this is as expected 
https://rt-sso.linuxfoundation.org/Ticket/Display.html?id=75788

**Comment by schannamallu** [comment]
@planetf1, 
an UNSTABLE from CLM jobs means that it failed a check on the CLM server (Nexus IQ) side. That's all something for the project to resolve, or for swinslow (or whoever is managing their licensing)

**Comment by planetf1** [comment]
Thanks for clarifying. that's fine. we have things to do. Can you close.
